language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-kiwi' ]; then cd .. && eval "mv $currentfolder generator-kiwi" && cd generator-kiwi; fi

